import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Nexora – Sync GitHub & GitLab Instantly</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
  <style>
    body {
      margin: 0;
      font-family: 'Inter', sans-serif;
      background: #0f172a;
      color: white;
    }

    header {
      padding: 20px 10%;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .logo {
      font-weight: 700;
      font-size: 20px;
    }

    .hero {
      text-align: center;
      padding: 100px 20px;
    }

    .hero h1 {
      font-size: 48px;
      margin-bottom: 20px;
    }

    .hero p {
      font-size: 18px;
      color: #cbd5e1;
      max-width: 600px;
      margin: 0 auto 40px;
    }

    .btn {
      padding: 12px 24px;
      background: #6366f1;
      border: none;
      border-radius: 8px;
      color: white;
      font-weight: 600;
      cursor: pointer;
      text-decoration: none;
    }

    .section {
      padding: 80px 10%;
      text-align: center;
    }

    .features {
      display: flex;
      justify-content: space-around;
      flex-wrap: wrap;
      gap: 40px;
    }

    .feature {
      max-width: 300px;
    }

    .waitlist {
      background: #1e293b;
      padding: 60px 20px;
      text-align: center;
    }

    .waitlist input {
      padding: 12px;
      border-radius: 6px;
      border: none;
      width: 250px;
      margin-right: 10px;
    }

    footer {
      text-align: center;
      padding: 40px;
      color: #94a3b8;
    }
  </style>
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
